from typing import Self

from .negatives import Negative
from .trait import ALL_TYPES, ExpressionTrait, ScaledSymbolTrait, SymbolTrait, SymbolVal


class Symbol[T: SymbolVal](SymbolTrait):
    __slots__ = ("_value",)
    _value: T

    def __init__(self, value: T) -> None:
        self._value = value

    def __str__(self) -> str:
        return f"{self._value!s}"

    def __hash__(self) -> int:
        return hash(self._value)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, SymbolTrait):
            return False
        return self._value == other.value

    def __neg__(self) -> Negative[Self]:
        return Negative(self)

    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __radd__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rsub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rmul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rtruediv__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rpow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rmod__(self, other: ALL_TYPES) -> ExpressionTrait: ...

    @property
    def value(self) -> T:
        return self._value


class ScaledSymbol(ScaledSymbolTrait):
    __slots__ = ("_scale", "_symbol")
    _scale: float | int
    _symbol: SymbolTrait

    def __init__(self, scaled: float, symbol: SymbolTrait) -> None:
        self._symbol = symbol
        self._scale = scaled

    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __neg__(self) -> ScaledSymbolTrait: ...
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __radd__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rsub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __mul__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    def __rmul__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    def __div__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    def __rtruediv__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rpow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    def __rmod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    def value(self) -> SymbolTrait:
        return self._symbol

    @property
    def scale(self) -> float | int:
        return self._scale
