import abc
import enum
from typing import TYPE_CHECKING, Literal

from cheartpy.fe.trait._basic import IVariable

if TYPE_CHECKING:
    from collections.abc import Sequence


type ALL_TYPES = NegativeTrait | SymbolTrait | ExpressionTrait | FunctionTrait | int | float
type POSITIVE_TYPES = SymbolTrait | ExpressionTrait | FunctionTrait | int | float
SymbolVal = str | IVariable
MATH_OPS = Literal[r"+", r"-", r"*", r"/", r"**", r"%", r"!"]
FUNC_OPS = Literal[r"sin", r"cos", r"abs", r"exp"]
SPECIALS = Literal[r"t"]


class MathOperator(enum.StrEnum):
    ADD = r"+"
    SUB = r"-"
    MUL = r"*"
    DIV = r"/"
    POW = r"**"
    MOD = r"%"
    NEG = r"!"


class NegativeTrait(abc.ABC):
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> POSITIVE_TYPES: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def value(self) -> POSITIVE_TYPES: ...


class SymbolTrait(abc.ABC):
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> NegativeTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def value(self) -> SymbolVal: ...


class ExpressionTrait(abc.ABC):
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> NegativeTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def left(self) -> ALL_TYPES: ...
    @property
    @abc.abstractmethod
    def op(self) -> MathOperator: ...
    @property
    @abc.abstractmethod
    def right(self) -> ALL_TYPES: ...


class FunctionTrait(abc.ABC):
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> NegativeTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def name(self) -> str: ...
    @property
    @abc.abstractmethod
    def args(self) -> Sequence[ALL_TYPES]: ...
