import abc
from typing import Literal

type SYM_TYPES = "ISymbol | IExpression | INumber"
MATH_OPS = Literal[r"+", r"-", r"*", r"/", r"**", r"%"]
FUNC_OPS = Literal[r"sin", r"cos", r"abs", r"exp"]


class IOperator(abc.ABC):
    @abc.abstractmethod
    def __init__(self, op: Literal[MATH_OPS, FUNC_OPS]) -> None: ...
    @abc.abstractmethod
    def __repr__(self) -> str: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...


class INumber(abc.ABC):
    @abc.abstractmethod
    def __init__(self, val: float) -> None: ...
    @abc.abstractmethod
    def __repr__(self) -> str: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __add__(self, other: SYM_TYPES) -> SYM_TYPES: ...
    @abc.abstractmethod
    def __sub__(self, other: SYM_TYPES) -> SYM_TYPES: ...
    @abc.abstractmethod
    def __mul__(self, other: SYM_TYPES) -> SYM_TYPES: ...
    @abc.abstractmethod
    def __div__(self, other: SYM_TYPES) -> SYM_TYPES: ...
    @abc.abstractmethod
    def __pow__(self, other: SYM_TYPES) -> SYM_TYPES: ...
    @abc.abstractmethod
    def __mod__(self, other: SYM_TYPES) -> SYM_TYPES: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...


class ISymbol(abc.ABC):
    @abc.abstractmethod
    def __init__(self, name: str) -> None: ...
    @abc.abstractmethod
    def __repr__(self) -> str: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __add__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __sub__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __mul__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __div__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __pow__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __mod__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...


class IExpression(abc.ABC):
    @abc.abstractmethod
    def __init__(self, left: SYM_TYPES, op: IOperator, right: SYM_TYPES) -> None: ...
    @abc.abstractmethod
    def __repr__(self) -> str: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __add__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __sub__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __mul__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __div__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __pow__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __mod__(self, other: SYM_TYPES) -> "IExpression": ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
