import abc
import enum
from typing import TYPE_CHECKING, Literal, NamedTuple

from cheartpy.fe.trait._basic import IVariable

if TYPE_CHECKING:
    from collections.abc import Sequence


type ALL_TYPES = ExpressionTrait | SymbolTrait | FunctionTrait | int | float
type NEGATABLE_TYPES = ExpressionTrait | SymbolTrait | FunctionTrait
type SCALABLE_TYPES = SymbolTrait | FunctionTrait
type IMMUTABLE_TYPES = SymbolTrait | FunctionTrait
SymbolVal = str | IVariable
MATH_OPS = Literal[r"+", r"-", r"*", r"/", r"**", r"%"]
FUNC_OPS = Literal[r"sin", r"cos", r"abs", r"exp"]
SPECIALS = Literal[r"t"]


class MathOperator(enum.StrEnum):
    ADD = r"+"
    SUB = r"-"
    MUL = r"*"
    DIV = r"/"
    POW = r"**"
    MOD = r"%"


class ExpressionTuple(NamedTuple):
    left: ALL_TYPES
    op: MathOperator
    right: ALL_TYPES


class SymbolTrait(abc.ABC):
    @abc.abstractmethod
    def __init__(self, value: SymbolVal) -> None: ...
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __radd__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rsub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rmul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rtruediv__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rpow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rmod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def value(self) -> SymbolVal: ...


class ScaledSymbolTrait(abc.ABC):
    @abc.abstractmethod
    def __init__(self, scaled: float, symbol: SymbolTrait) -> None: ...
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> ScaledSymbolTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __radd__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rsub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    @abc.abstractmethod
    def __rmul__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    @abc.abstractmethod
    def __rtruediv__(self, other: ALL_TYPES) -> ScaledSymbolTrait | SymbolTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rpow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rmod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def value(self) -> SymbolTrait: ...
    @property
    @abc.abstractmethod
    def scale(self) -> float: ...


class ExpressionTrait(abc.ABC):
    @abc.abstractmethod
    def __init__(self, left: ALL_TYPES, op: MathOperator, right: ALL_TYPES) -> None: ...
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __radd__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __rsub__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __rmul__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __rtruediv__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __rpow__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @abc.abstractmethod
    def __rmod__(self, other: ALL_TYPES) -> ALL_TYPES: ...
    @property
    @abc.abstractmethod
    def left(self) -> ALL_TYPES: ...
    @property
    @abc.abstractmethod
    def op(self) -> MathOperator: ...
    @property
    @abc.abstractmethod
    def right(self) -> ALL_TYPES: ...


class FunctionTrait(abc.ABC):
    @abc.abstractmethod
    def __init__(self, name: str, *arg: ALL_TYPES) -> None: ...
    @abc.abstractmethod
    def __str__(self) -> str: ...
    @abc.abstractmethod
    def __hash__(self) -> int: ...
    @abc.abstractmethod
    def __eq__(self, other: object) -> bool: ...
    @abc.abstractmethod
    def __neg__(self) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __add__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __radd__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __sub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rsub__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rmul__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __div__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rtruediv__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __pow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rpow__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __mod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @abc.abstractmethod
    def __rmod__(self, other: ALL_TYPES) -> ExpressionTrait: ...
    @property
    @abc.abstractmethod
    def name(self) -> str: ...
    @property
    @abc.abstractmethod
    def args(self) -> Sequence[ALL_TYPES]: ...
