import numpy as np
from pytools.arrays import A2
from pytools.result import Result

def normalize_by_row[F: np.floating](vals: A2[F]) -> Result[A2[F]]: ...
def orthonormalize_by_row[F: np.floating](vals: A2[F]) -> A2[F]: ...
