__all__ = ["PFile"]
import dataclasses as dc
from typing import TextIO

from .trait import (
    ICheartBasis,
    ICheartTopology,
    IDataPointer,
    IExpression,
    IProblem,
    ISolverGroup,
    ISolverMatrix,
    ISolverSubGroup,
    ITimeScheme,
    ITopInterface,
    IVariable,
)

@dc.dataclass(slots=True)
class PFile:
    h: str = ""
    output_dir: str | None = None
    def SetOutputPath(self, path: str) -> None: ...
    def AddTimeScheme(self, *time: ITimeScheme) -> None: ...
    def AddDataPointer(self, *var: IDataPointer) -> None: ...
    def AddBasis(self, *basis: ICheartBasis | None) -> None: ...
    def AddTopology(self, *top: ICheartTopology) -> None: ...
    def AddInterface(self, *interfaces: ITopInterface) -> None: ...
    def AddVariable(self, *var: IVariable) -> None: ...
    def AddExpression(self, *expr: IExpression) -> None: ...
    def AddProblem(self, *prob: IProblem) -> None: ...
    def AddMatrix(self, *mat: ISolverMatrix) -> None: ...
    def AddSolverSubGroup(self, *subgroup: ISolverSubGroup) -> None: ...
    def AddSolverGroup(self, *grp: ISolverGroup) -> None: ...
    def SetExportFrequency(self, *vars: IVariable, freq: int = 1) -> None: ...
    def write(self, f: TextIO) -> None: ...
