from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Unpack

from pytools.arrays import A1
from pytools.result import Result

from ._parser import APIKwargsFind, APIKwargsIndex, TimeSeriesKwargs
from ._trait import TimeSerie

def cheart2vtu_find(**kwargs: Unpack[APIKwargsFind]) -> None: ...
def cheart2vtu_index(**kwargs: Unpack[APIKwargsIndex]) -> None: ...
def cheart2vtu_cli(cmd_args: Sequence[str] | None = None) -> None: ...
def main_cli(cmdline: Sequence[str] | None = None) -> None: ...
def create_time_series_json(vtus: Iterable[Path | str], times: A1) -> TimeSerie: ...
def create_time_series_api(**kwargs: Unpack[TimeSeriesKwargs]) -> Result[None]: ...
def create_time_series_cli(cmdline: Sequence[str] | None = None) -> None: ...
