from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Literal, Unpack, overload

import numpy as np
from pytools.arrays import A1
from pytools.result import Result

from ._parser.types import APIKwargsFind, APIKwargsIndex
from ._time_series import TimeSeriesKwargs
from ._trait import TIME_SERIES

@overload
def cheart2vtu_api(cmd: Literal["find"], **kwargs: Unpack[APIKwargsFind]) -> None: ...
@overload
def cheart2vtu_api(cmd: Literal["index"], **kwargs: Unpack[APIKwargsIndex]) -> None: ...
def cheart2vtu_find(**kwargs: Unpack[APIKwargsFind]) -> None: ...
def cheart2vtu_index(**kwargs: Unpack[APIKwargsIndex]) -> None: ...
def cheart2vtu_cli(cmd_args: Sequence[str] | None = None) -> None: ...
def main_cli(cmdline: Sequence[str] | None = None) -> None: ...
def create_time_series_json[F: np.floating](
    vtus: Iterable[Path | str], times: A1[F]
) -> TIME_SERIES: ...
def create_time_series_api(**kwargs: Unpack[TimeSeriesKwargs]) -> Result[None]: ...
def create_time_series_cli(cmdline: Sequence[str] | None = None) -> None: ...
