# ruff: noqa: PYI011
from pathlib import Path

import numpy as np
from pytools.arrays import A1, A2, Arr, DType

def read_array_int[I: np.integer](
    name: Path | str, skip: int = 0, *, dtype: DType[I] = np.intc
) -> Arr[tuple[int, ...], I]: ...
def read_array_float[F: np.floating](
    name: Path | str, skip: int = 0, *, dtype: DType[F] = np.float64
) -> Arr[tuple[int, ...], F]: ...
def write_array_int[T: np.integer](name: Path | str, arr: A2[T]) -> None: ...
def write_array_float[T: np.floating](name: Path | str, arr: A2[T]) -> None: ...
def is_binary(filename: Path | str) -> bool: ...
def fix_ch_sfx[T: (Path | str)](prefix: T, suffix: str = "_FE.") -> T: ...
def check_for_meshes(*names: str, home: Path | None = None, bc: bool = True) -> bool: ...
def chread_d_utf[F: np.floating](file: Path | str, *, dtype: DType[F] = np.float64) -> A2[F]: ...
def chread_d_bin[F: np.floating](file: Path | str, *, dtype: DType[F] = np.float64) -> A2[F]: ...
def chread_d[F: np.floating](file: Path | str, *, dtype: DType[F] = np.float64) -> A2[F]: ...
def chread_data[F: np.floating](file: Path | str, *, dtype: DType[F] = np.float64) -> A2[F]: ...
def chread_t_utf[I: np.integer](file: Path | str, *, dtype: DType[I] = np.intc) -> A2[I]: ...
def chread_b_utf[I: np.integer](file: Path | str, *, dtype: DType[I] = np.intc) -> A2[I]: ...
def chread_time_utf[F: np.floating, I: np.integer](
    file: Path | str, *, dtype: DType[I] = np.intp, ftype: DType[F] = np.float64
) -> A1[F]: ...
def chread_header_utf(file: Path | str) -> tuple[int, int]: ...
def chwrite_d_utf[T: np.floating, S: tuple[int, ...]](
    file: Path | str, data: Arr[S, T]
) -> None: ...
def chwrite_d_binary[T: np.floating](file: Path | str, arr: A2[T]) -> None: ...
def chwrite_t_utf[T: np.integer](file: Path | str, data: A2[T], nn: int | None = None) -> None: ...
def chwrite_iarr_utf[T: np.integer](file: Path | str, data: A2[T]) -> None: ...
def chwrite_str_utf[T: np.str_](file: Path | str, data: A2[T]) -> None: ...
def chwrite_time_utf[F: np.floating](file: Path | str, data: A1[F]) -> None: ...
