from collections.abc import Sequence
from pathlib import Path
from typing import Unpack

from ._types import CheartErrorCode as CheartErrorCode
from ._types import PrepKwargs as PrepKwargs
from ._types import SolverKwargs as SolverKwargs

def run_prep(pfile: Path | str, **kwargs: Unpack[PrepKwargs]) -> int: ...
def run_problem(pfile: Path | str, **kwargs: Unpack[SolverKwargs]) -> int: ...
def solver_cli(args: Sequence[str] | None = None) -> int: ...
def prep_cli(args: Sequence[str] | None = None) -> int: ...
