import dataclasses as dc
from typing import TextIO

from .trait import (
    ICheartBasis,
    ICheartTopology,
    IDataPointer,
    IExpression,
    IProblem,
    ISolverGroup,
    ISolverMatrix,
    ISolverSubGroup,
    ITimeScheme,
    ITopInterface,
    IVariable,
)

__all__ = ["PFile"]

@dc.dataclass(slots=True)
class PFile:
    h: str = ""
    output_dir: str | None = None
    def set_outputpath(self, path: str) -> None: ...
    def add_timescheme(self, *time: ITimeScheme) -> None: ...
    def add_datapointer(self, *var: IDataPointer) -> None: ...
    def add_basis(self, *basis: ICheartBasis | None) -> None: ...
    def add_topology(self, *top: ICheartTopology) -> None: ...
    def add_interface(self, *interfaces: ITopInterface) -> None: ...
    def add_variable(self, *var: IVariable) -> None: ...
    def add_expression(self, *expr: IExpression) -> None: ...
    def add_problem(self, *prob: IProblem) -> None: ...
    def add_matrix(self, *mat: ISolverMatrix) -> None: ...
    def add_solversubgroup(self, *subgroup: ISolverSubGroup) -> None: ...
    def add_solvergroup(self, *grp: ISolverGroup) -> None: ...
    def set_exportfrequency(self, *var: IVariable, freq: int = 1) -> None: ...
    def write(self, f: TextIO) -> None: ...
